---
apiVersion: v1
kind: Service
metadata:
  name: ttm-as-a-service
spec:
  ports:
    - name: webhook
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    deploymentconfig: ttm-as-a-service
