
check:
  - thoth-build
build:
  base-image: quay.io/thoth-station/s2i-thoth-ubi8-py38:v0.34.1
  build-stratergy: "Source"
  custom_tag: "latest"
  registry: "quay.io"
  registry-org: "thoth-station"
  registry-project: "ttm-as-a-service"
  registry-secret: "thoth-station-thoth-pusher-secret"
deploy:
  project-org: "thoth-station"
  project-name: "ttm-as-a-service"
  image-name: "ttm-as-a-service"
#  overlay-contextpath: "sefkhet-abwy/overlays/ocp/imagestreamtag.yaml"
